server:
  port: 8086

spring:
  application:
    name: pay
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:coupon
    username: coupon
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

axoniq:
  console:
    credentials=9f881e3c-0:3bb299ad542d426ab9a3375de21fd3e8: